---

- name: copy dotfiles to user dir
  when: not shell_system_wide_install
  copy:
    src={{ item }}
    dest={{ shell_user_dir }}/.{{ item }}
    owner={{ shell_user }}
  with_items:
    - bash_profile
    - bashrc
    - exports
    - aliases
    - functions
    - inputrc
    - vimrc
    - screenrc
    - tmux.conf

- name: install app-specific init files system-wide
  when: shell_system_wide_install
  copy:
    src={{ item }}
    dest=/etc/
    mode=a+r
    owner=root
    group=root
  become: yes
  with_items:
    - vimrc
    - inputrc
    - screenrc
    - tmux.conf

- name: install shell init files system-wide
  when: shell_system_wide_install
  copy:
    src={{ item }}
    dest=/etc/profile.d/{{ item }}.sh
    mode=a+r
    owner=root
    group=root
  become: yes
  with_items:
    - bashrc-system
    - exports-system
    - aliases
    - functions
